name: build.yaml Build
 
on: workflow_dispatch # when to trigger this. Here, manually
jobs:
  build_and_test:
    name: "Build and test"
    strategy:
      matrix:
        os: [windows-latest] # we build on GitHub-provided Windows image
    runs-on: ${{ matrix.os }} # use value from the matrix
    steps:
    - name: Install Ninja (windows)    # Ninja is not available in GitHub-provided images,
                                       # see https://github.com/actions/runner-images/issues/514
      run: choco install ninja         # So let's install it through Chocolatey
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        aqtversion: '==3.1.*'
        version: '6.9.1'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64'
        modules: 'qtcharts qtnetworkauth'
    - uses: ilammy/msvc-dev-cmd@v1 # This action essentially calls vcvarsall.bat for the latest VS in the runner for x64
    - uses: actions/checkout@v3    # Actually check out the sources. GH Actions can run for events that may not require
                                   # sources (e.g. when someone comments on an issue)

    - name: Build
      run: qmake qt-qmake-example-project.pro

    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: |
          ~/build/release/*
        compression-level: 0

