name: build.yaml Build
 
on: workflow_dispatch # when to trigger this. Here, manually
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
#    - name: Install Ninja (windows)    # Ninja is not available in GitHub-provided images,
#                                       # see https://github.com/actions/runner-images/issues/514
#      run: choco install ninja         # So let's install it through Chocolatey

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        aqtversion: '==3.1.*'
        version: '6.9.1'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64'
        modules: 'qtcharts qtnetworkauth'
    - uses: ilammy/msvc-dev-cmd@v1 # This action essentially calls vcvarsall.bat for the latest VS in the runner for x64
    - uses: actions/checkout@v3    # Actually check out the sources. GH Actions can run for events that may not require
                                   # sources (e.g. when someone comments on an issue)

    - name: Install NSIS
      run: |
           Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
           scoop bucket add extras
           scoop install nsis

    - name: Compile
      run: qmake qt-qmake-example-project.pro CONFIG+=release
           nmake

    - name: Deploy
      run: |
           mkdir bin
           move build/${{env.EXECUTABLE}}.exe bin
           windeployqt bin/${{env.EXECUTABLE}}.exe -qmldir="${{env.QML_DIR_WIN}}" --compiler-runtime
           mkdir "${{env.APPLICATION}}"
           move bin "${{env.APPLICATION}}"
#           xcopy deploy\windows\resources\icon.ico "${{env.APPLICATION}}"

    - name: Upload exe
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.EXECUTABLE}}.exe
        path: deploy/windows/nsis/${{env.EXECUTABLE}}-${{env.VERSION}}-Windows.exe
        compression-level: 0
