name: Build
 
on: workflow_dispatch # when to trigger this. Here, manually
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        aqtversion: '==3.1.*'
        version: '6.9.1'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64'
        modules: 'qtcharts qtnetworkauth'
    - uses: ilammy/msvc-dev-cmd@v1 # This action essentially calls vcvarsall.bat for the latest VS in the runner for x64
    - uses: actions/checkout@v3    # Actually check out the sources. GH Actions can run for events that may not require
                                   # sources (e.g. when someone comments on an issue)

    - name: Install NSIS
      run: |
           Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
           scoop bucket add extras
           scoop install nsis
    
    - name: Install jom
      run: choco install jom
      
    - name: QMake
      run: qmake qt-qmake-example-project.pro CONFIG+=release

    - name: Compile
      run: jom

    - name: Find exe
      id: find_exe
      run: |
        $exe = Get-ChildItem -Recurse -Filter "qt-qmake-test.exe" | Select-Object -First 1
        echo "EXE_PATH=$($exe.FullName)" >> $env:GITHUB_OUTPUT
        echo "EXE_DIR=$($exe.DirectoryName)" >> $env:GITHUB_OUTPUT
        Write-Host "Found exe at: $($exe.FullName)"
          
    - name: Deploy
      run: |
           mkdir bin
           move "${{ steps.find_exe.outputs.EXE_PATH }}" bin
           windeployqt bin/qt-qmake-test.exe --compiler-runtime
#           xcopy deploy\windows\resources\icon.ico "${{env.APPLICATION}}"

#    - name: Make NSIS installer
#      run: |
#           move "qt-qmake-test" deploy\windows\nsis\
#           cd deploy\windows\nsis
#           makensis /X"SetCompressor /FINAL lzma" setup.nsi
#           ren *.exe qt-qmake-test.exe

    - name: Upload exe
      uses: actions/upload-artifact@v4
      with:
        name: qt-qmake-test
        path: bin/
        compression-level: 0
